<?php
/**
 * This file is part of the TeamNeustaGmbH/m2t3 package.
 *
 * Copyright (c) 2017 neusta GmbH | Ein team neusta Unternehmen
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 *
 * @license https://opensource.org/licenses/BSD-3-Clause BSD-3-Clause License
 */

use Magento\Framework\App\Action\Action;

/** @var \TeamNeustaGmbh\M2T3\Block\Catalog\Product\View $block */
/** @var \Magento\Catalog\Model\Product $product */
$_product = $this->getProduct();
?>
<div class="product-item-info">
    <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
       title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>">
        <?php echo $block->getImage($_product, 'product_page_image_small')->toHtml(); ?>
    </a>
    <div class="product-item-details">
        <strong class="product-item-name">
            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
               title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>)" class="product-item-link">
                <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
            </a>
        </strong>
        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
        <div class="product-item-actions">
            <div class="actions-primary">
                <?php if ($_product->isSaleable()): ?>
                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                        <button type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>"
                                class="action tocart primary"
                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'>
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    <?php else: ?>
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                            <?php echo $block->getBlockHtml('formkey')?>
                            <button type="submit"
                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                            </button>
                        </form>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if ($_product->getIsSalable()): ?>
                        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                        </div>
                    <?php else: ?>
                        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>