<?php
/**
 * This file is part of the TeamNeustaGmbH/m2t3 package.
 *
 * Copyright (c) 2017 neusta GmbH | Ein team neusta Unternehmen
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 *
 * @license https://opensource.org/licenses/BSD-3-Clause BSD-3-Clause License
 */

use Magento\Framework\App\Action\Action;

/** @var \TeamNeustaGmbh\Magentypo\Block\Catalog\Product\Renderer\DefaultRenderer $block */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProductById($block->getProductIds()[0]);
?>
<div class="product-item-info">
    <a class="product-item-photo"
       href="<?php echo $product->getProductUrl() ?>"
       title="<?php echo $block->stripTags($product->getName(), null, true) ?>">
        <?php echo $block->getImage($product, 'product_page_image_small')->toHtml(); ?>
    </a>
    <div class="product-item-details">
        <strong class="product-item-name">
            <a href="<?php echo $product->getProductUrl() ?>"
               title="<?php echo $block->stripTags($product->getName(), null, true) ?>)"
               class="product-item-link">
                <?php echo $block->renderProductAttribute($product, $product->getName(), 'name') ?>
            </a>
        </strong>
        <?php echo $block->getProductPrice($product); ?>
        <div class="product-item-actions">
            <div class="actions-primary">
                <?php if ($product->isSaleable()): ?>
                    <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                        <button type="button" title="<?php echo __('Add to Cart') ?>"
                                class="action tocart primary"
                                data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($product) ?>"}}'>
                            <span><?php echo __('Add to Cart') ?></span>
                        </button>
                    <?php else: ?>
                        <?php $postParams = $block->getAddToCartPostParams($product); ?>
                        <form data-role="tocart-form"
                              action="<?php echo $postParams['action']; ?>"
                              method="post">

                            <input type="hidden"
                                   name="product"
                                   value="<?php echo $postParams['data']['product']; ?>">

                            <input type="hidden"
                                   name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                   value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">

                            <?php echo $block->getBlockHtml('formkey')?>

                            <button type="submit"
                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary">
                                <span><?php echo __('Add to Cart') ?></span>
                            </button>
                        </form>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if ($product->getIsSalable()): ?>
                        <div class="stock available" title="<?php echo __('Availability') ?>">
                            <span><?php echo __('In stock') ?></span>
                        </div>
                    <?php else: ?>
                        <div class="stock unavailable" title="<?php echo __('Availability') ?>">
                            <span><?php echo __('Out of stock') ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
